heat_template_version: 2013-05-23

description: Template that installs a php client server.

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for server. Please use an Ubuntu based image.
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
  key:
    type: string
    label: Key name
    description: Name of key-pair to be installed on the compute instance.
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach server to.
  public_network:
    type: string
    label: Public network name or ID
    description: Network to attach server to.
  service_server:
    type: string
    label: php service server
    description: IP address of the php service server.
  security_group:
    type: string
    label: LAMP security group
    description: Name of LAMP security group

resources:
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: { get_resource: wh }
      count: 1
      timeout: 600

  wh:
    type: OS::Heat::WaitConditionHandle

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_network }
      security_groups:
        - { get_param: security_group }
        - default

  client_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __service_ip__: { get_param: service_server }
            wc_notify: { get_attr: ['wh', 'curl_cli'] }
          template: |
            #!/bin/bash
            apt-get update
            apt-get -y upgrade
            sudo debconf-set-selections <<< 'lamp-server^ mysql-server/root_password password grad'
            sudo debconf-set-selections <<< 'lamp-server^ mysql-server/root_password_again password grad'
            apt-get -y install git
            apt-get -y install lamp-server^
            cd /var/www/html/
            wget --no-check-certificate https://raw.githubusercontent.com/nikoladom91/ARIKS2016/master/Skripte/Heat/resursi/client.php
            wget --no-check-certificate https://raw.githubusercontent.com/nikoladom91/ARIKS2016/master/Skripte/Heat/resursi/nusoap.php
            echo "__service_ip__" >> serviceIP.txt
            
            # notify heat that we are done here
            wc_notify -k --data-binary '{"status": "SUCCESS"}'
            
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }

outputs:
  name:
    description: Name of the Client instance.
    value: { get_attr: [client_instance, name] }
  ip:
    description: The IP address of the Client instance.
    value: { get_attr: [floating_ip, floating_ip_address] }
